import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/header";

export default function Layout({children, metaTitle, metadescription}) {
 return (
  <div>
    <Head>
    <title> Create Next App - {metaTitle}</title>
    <meta name="description" content={metadescription || "Generated by create next app"} />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <Header />
   {children}
   <Footer />
  </div>
 );
}
